Mapr warnings fix
pythian/puppet-cloudera pull request #2
Opened 2017-03-15 21:58 UTC by pythianmantoani

Fixed Warnings on MapReduce
Implemented configurations for mapred_reduce_tasks, mapred_submit_replication and mapred_job_tracker_handler_count

2017-03-16 13:33 UTC, thiagonache requested changes

2017-03-16 13:33 UTC, thiagonache commented on manifests/roles/server.pp
> +    items_config => [{ "name" => "mapred_reduce_tasks", "value" => "3" },{ "name" => "mapred_submit_replication", "value" => "3" }],
value here cannot be hardcoded

2017-03-16 13:33 UTC, thiagonache commented on manifests/roles/server.pp
> +    items_config => [{ "name" => "jobtracker_mapred_local_dir_list", "value" => "/dfs/mapreduce/jobtracker"},{ "name" => "mapred_job_tracker_handler_count", "value" => "25"}],
value here cannot be hardcoded

2017-03-17 20:30 UTC, pythianmantoani commented
Please use branch mapreduce_warnings on Terraform to test this PR

2017-03-20 17:39 UTC, merged